url: https://andy6804tw.github.io
baseurl: /ecare-cjcu-sheepherd-blog/

# Site settings
title: 106學年度教育部資訊志工
email: andy6804tw@yahoo.com.tw
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: 朱瓊珮 老師
  pic: 1-1
  pic2: 1-2
  position: 副領隊
  contact:
    - title: envelope
      url: michelle1005@mail.cjcu.edu.tw
  social:
    - title: user
      url: http://dweb.cjcu.edu.tw/iid/teacher/IN

- name: 吳南烈 老師
  pic: 1-1
  pic2: 2-2
  position: 領隊
  contact:
    - title: envelope
      url: chun@mail.cjcu.edu.tw
  social:
    - title: user
      url: http://dweb.cjcu.edu.tw/csie/teacher/CS

- name: 蘇益生 老師
  pic: 3-1
  pic2: 3-2
  position: 副領隊
  contact:
    - title: envelope
      url: yssu@mail.cjcu.edu.tw
  social:
    - title: user
      url: http://dweb.cjcu.edu.tw/csie/teacher/CS

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/groups/1585709211677714/
  - title: envelope
    url: chun@mail.cjcu.edu.tw
  - title: github
    url: https://github.com/andy6804tw/ecare-cjcu-sheepherd-blog

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
